<a href="https://colab.research.google.com/github/ajaymaliya597/Machine_Learning/blob/main/pandasNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
# Data type
#  Series

In [ ]:
import numpy as np
arr = np.array([1,2,3,4]) + 1
arr[0]

In [ ]:
# Series in Pandas
# Series is a one dimensional data in which the indices
# are also shown..
s = pd.Series([1,2,3,4])
s[0]

In [ ]:
# A dataframe is a data type present in pandas in which
# the data is stored into the form of rows and columns
# Syntax -> pd.DataFrame(dictionary)
pd.DataFrame({
    'A':[1,2,3, 4],
    'B':[10, 20, 30, 40]
})

In [ ]:
s = pd.Series([1.1, 2.1, 3, 4])
s[0]

In [ ]:
s.size

In [ ]:
s.dtype

In [ ]:
s[0:2]

In [ ]:
# Dataframe
# By using dictionary
# by using list
pd.DataFrame(
  [
      ['Aman', 20],
      ['naman', 35],
      ['vikash', 50]
  ],
  columns=['Name', 'Marks']
)

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.sample(5)

In [ ]:
import pandas as pd

df = pd.read_csv('/content/CarPrice_Assignment.csv')

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df['CarName']

In [ ]:
df.columns

In [ ]:
df[['doornumber', 'carbody', 'drivewheel']]

In [ ]:
'four'

In [ ]:
df[df['doornumber'] == 'two']

In [ ]:
cat_cols = df.select_dtypes(include='object').columns
num_cols = df.select_dtypes(exclude='object').columns

In [ ]:
df[num_cols]

In [ ]:
df[cat_cols]

In [ ]:
# Loc & Iloc
# Coditional selection of the entries
# How to handle the missing or null values..

In [ ]:
import pandas as pd
df = pd.read_csv('/content/train.csv')

In [ ]:
df.shape

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
cat_cols = df.select_dtypes(include='object').columns
num_cols = df.select_dtypes(exclude='object').columns

In [ ]:
num_cols

In [ ]:
cat_cols

In [ ]:
df[cat_cols]

In [ ]:
df[num_cols]

In [ ]:
df.iloc[0:3]

In [ ]:
df.loc[0:3]

In [ ]:
import numpy as np

In [ ]:
data = pd.DataFrame({
    'Age':[20, 23, 24, np.nan],
    'Height':[np.nan, 180, 165, 177],
    'Name':['Maan', np.nan, 'Naman', 'Vikash']
}, index=['a', 'b', 'c', 'd'])

# data.loc['a':'c']
# new_data = data.loc['a':'b', 'Height':'Name']
# # To select a particular row from the dataframe on the
# # basis of the labels then we must have to use the loc
# # df.loc[row_slicing, column_slicing]
# new_data.to_csv('new_data.csv', index=False)
data

In [ ]:
# Iloc
data.iloc[0:3, 0:2]
# Iloc is known as integer based indexing into which
# we basically select the particular row and column on the
# basis of integer based indexing. Into this the end index
# exclusive
# syntax -> df.iloc[row_slicing, column_slicing]

In [ ]:
data.isna()

In [ ]:
# How to handle the missing values of the data frame
# So, first of all we have to check whether the data is
# having any null value or not ?
data.isna().sum()

In [ ]:
# There are two methods for null value handling
# Dropping the null values
# Impute the null values

In [ ]:
data.dropna()
# if there is very less amount of the null present in the
# dataframe then we can use the dropna..but it could lead to
# the data loss

In [ ]:
df[cat_cols].isna().sum()

In [ ]:
df[num_cols].isna().sum()

In [ ]:
# Imputing the numerical columns which are having the null values
# it can be imputed by two ways -> mean, median
# if the column is having any extreme value (outlier) then you must have
# to impute that with median
# if the columns is not having any outlier then we must have to fill that
# with mean..

In [ ]:
df['LotFrontage'].isna().sum()

In [ ]:
df['LotFrontage'].fillna(df['LotFrontage'].mean(), inplace=True)

In [ ]:
df['LotFrontage'].isna().sum()

In [ ]:
df['Alley'].isna().sum()

In [ ]:
df.drop('Alley', axis=1, inplace=True)

In [ ]:
df.shape

In [ ]:
df['LotShape'].isna().sum()

In [ ]:
df['BsmtCond'].isna().sum()

In [ ]:
mode = df['BsmtCond'].mode()[0]

In [ ]:
df['BsmtCond'].fillna(mode, inplace=True)

In [ ]:
df['BsmtCond'].isna().sum()

In [ ]:
df['BsmtCond'].value_counts()

In [ ]:
cat_cols

In [ ]:
# Handling Null Values

# Data
# Categorical -> null value -> mode imputation
# Numerical -> null value -> impute with median or mean

In [ ]:
# Column 50 % > null values -> Drop particular
# 1% or 2% -> Drop using dropna.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/train.csv')

In [ ]:
df['MSZoning'].unique()

In [ ]:
df[df['LotArea'] > 10000]

In [ ]:
df[df['MSZoning'] == 'RL']

In [ ]:
df

In [ ]:
for col in df.columns:
  print(col)

In [ ]:
data = pd.DataFrame({
    'Col1':[20, 30, 35, 42, 31],
    'Col2':[35, 48, 45, 45, 41],
    'Full':['Aman Singh', 'naman Singh', 'shivam Sharma', 'Vishal Tawri', 'Yash Raj']
})

In [ ]:
data['Full'].str.split(' ')

In [ ]:
data['Name'].str.lower()

In [ ]:
data.sort_values(by='Col2')

In [ ]:
data.sort_values(by='Col1')

In [ ]:
# Add a new col
data['Col3'] = 10

In [ ]:
data['Col4'] = data['Col1'] + data['Col2']

In [ ]:
# Drop column
data.drop('Col3', axis=1, inplace=True)

In [ ]:
data

In [ ]:
# Value sorting

In [ ]:
data

In [ ]:
data

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.duplicated()

In [ ]:
import pandas as pd

# ==========================================================
# Load Dataset
# ==========================================================

df = pd.read_csv("/content/titanic-dataset.csv")

# ==========================================================
# AGGREGATION FUNCTIONS
# ==========================================================

# # Total Fare
# df["Fare"].sum()

# Average Fare
df["Fare"].mean()

# # Median Fare
# df["Fare"].median()

# # Most Frequent Fare
# df["Fare"].mode()

# # Minimum Fare
# df["Fare"].min()

# # Maximum Fare
# df["Fare"].max()

# # Count of Fare Records
# df["Fare"].count()

# # Standard Deviation
# df["Fare"].std()

np.float64(32.204207968574636)

In [ ]:
# ==========================================================
# GROUPBY
# ==========================================================

# Count Passengers by Gender
df.groupby("Sex").size()

# Count Passengers by Passenger Class
df.groupby("Pclass").size()

# Average Age by Gender
df.groupby("Sex")["Age"].mean()

# Average Fare by Passenger Class
df.groupby("Pclass")["Fare"].mean()

# Total Fare by Passenger Class
df.groupby("Pclass")["Fare"].sum()

# Maximum Fare by Passenger Class
df.groupby("Pclass")["Fare"].max()

# Minimum Fare by Passenger Class
df.groupby("Pclass")["Fare"].min()

# Survival Count by Gender
df.groupby("Sex")["Survived"].sum()

# Average Age by Passenger Class
df.groupby("Pclass")["Age"].mean()

In [ ]:
data = pd.DataFrame({
    'Dept':['IT','IT', 'Sales','IT', 'Sales'],
    'Salary':[20000, 22000, 15000, 20000, 18000]
})
data.groupby('Dept')['Salary'].agg(
    ['max', 'min', 'mean', 'sum']
)

         max    min          mean    sum
Dept
IT     22000  20000  20666.666667  62000
Sales  18000  15000  16500.000000  33000

In [ ]:
# ==========================================================
# MULTIPLE AGGREGATIONS
# ==========================================================

df.groupby("Pclass")["Fare"].agg(
    ["count","sum","mean","median","min","max","std"]
)

df.groupby("Sex")["Age"].agg(
    ["count","mean","median","min","max"]
)

# Multiple Columns

df.groupby("Pclass")[["Age","Fare"]].agg(
    {
        "Age":["mean","min","max"],
        "Fare":["sum","mean","max"]
    }
)

              Age                    Fare
             mean   min   max         sum       mean       max
Pclass
1       38.233441  0.92  80.0  18177.4125  84.154687  512.3292
2       29.877630  0.67  70.0   3801.8417  20.662183   73.5000
3       25.140620  0.42  74.0   6714.6951  13.675550   69.5500

In [ ]:

# ==========================================================
# REAL-WORLD ANALYSIS
# ==========================================================

# Which Passenger Class paid highest average fare?
df.groupby("Pclass")["Fare"].mean().sort_values(ascending=False)

# Which Gender survived the most?
df.groupby("Sex")["Survived"].sum()

# Passenger Count by Embarked Port
df.groupby("Embarked").size()

# Average Fare by Embarked Port
df.groupby("Embarked")["Fare"].mean()

In [ ]:

# ==========================================================
# CONCATENATION
# ==========================================================

# Vertical Concatenation

df1 = pd.DataFrame({
    "Emp_ID":[101,102],
    "Name":["Vinay","Aman"]
})

df2 = pd.DataFrame({
    "Emp_ID":[103,104],
    "Name":["Riya","Priya"]
})

vertical = pd.concat([df1,df2])

print(vertical)

   Emp_ID   Name
0     101  Vinay
1     102   Aman
0     103   Riya
1     104  Priya

In [ ]:

# ==========================================================
# Horizontal Concatenation
# ==========================================================

employee = pd.DataFrame({
    "Emp_ID":[101,102,103],
    "Name":["Vinay","Aman","Riya"]
})

salary = pd.DataFrame({
    "Salary":[50000,45000,60000],
    "Bonus":[5000,3000,7000]
})

horizontal = pd.concat(
    [employee,salary],
    axis=1
)

print(horizontal)

   Emp_ID   Name  Salary  Bonus
0     101  Vinay   50000   5000
1     102   Aman   45000   3000
2     103   Riya   60000   7000

In [ ]:

# ==========================================================
# MERGE
# ==========================================================

employees = pd.DataFrame({
    "Emp_ID":[101,102,103,104],
    "Name":["Vinay","Aman","Riya","Priya"]
})

salary = pd.DataFrame({
    "Emp_ID":[101,102,105],
    "Salary":[50000,45000,60000]
})

# ==========================================================
# INNER JOIN
# ==========================================================

inner = pd.merge(
    employees,
    salary,
    on="Emp_ID",
    how="right"
)

print(inner)

   Emp_ID   Name  Salary
0     101  Vinay   50000
1     102   Aman   45000
2     105    NaN   60000

In [ ]:

# ==========================================================
# LEFT JOIN
# ==========================================================

left = pd.merge(
    employees,
    salary,
    on="Emp_ID",
    how="left"
)

print(left)

# ==========================================================
# RIGHT JOIN
# ==========================================================

right = pd.merge(
    employees,
    salary,
    on="Emp_ID",
    how="right"
)

print(right)

# ==========================================================
# OUTER JOIN
# ==========================================================

outer = pd.merge(
    employees,
    salary,
    on="Emp_ID",
    how="outer"
)

print(outer)

In [ ]:

# ==========================================================
# BUSINESS QUESTIONS
# ==========================================================

# Top 10 Highest Fare Passengers
df.nlargest(10,"Fare")

# Passenger Count by Class
df.groupby("Pclass").size()

# Average Fare by Gender
df.groupby("Sex")["Fare"].mean()

# Survival Rate by Passenger Class
df.groupby("Pclass")["Survived"].mean()

# Highest Fare in Each Passenger Class
df.groupby("Pclass")["Fare"].max()

# Average Age of Survived Passengers
df[df["Survived"]==1]["Age"].mean()

# Average Fare by Embarked Port
df.groupby("Embarked")["Fare"].mean()

In [ ]:

# Create Sample Date Column

df["Booking_Date"] = [
    "2024-01-01","2024-01-05","2024-01-10","2024-01-12",
    "2024-01-15","2024-01-18","2024-01-20","2024-01-25",
    "2024-01-28","2024-02-01"
] * (len(df)//10) + ["2024-02-05"]*(len(df)%10)

# Convert into Datetime

df["Booking_Date"] = pd.to_datetime(df["Booking_Date"])

# Extract Year
df["Year"] = df["Booking_Date"].dt.year

# Extract Month
df["Month"] = df["Booking_Date"].dt.month

# Extract Day
df["Day"] = df["Booking_Date"].dt.day

# Extract Day Name
df["Day_Name"] = df["Booking_Date"].dt.day_name()

# Extract Month Name
df["Month_Name"] = df["Booking_Date"].dt.month_name()

print(df[["Booking_Date","Year","Month","Day","Day_Name"]].head())

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:

# ==========================================================
# APPLY()
# ==========================================================

# Create Age Category

def age_category(age):
    if pd.isnull(age):
        return "Unknown"
    elif age < 18:
        return "Child"
    elif age < 60:
        return "Adult"
    else:
        return "Senior Citizen"

df["Age_Category"] = df["Age"].apply(age_category)

In [ ]:
df['Double_age']=df["Age"].apply(lambda x:2*x)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Category,Double_age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult,44.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,76.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,52.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,70.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult,54.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult,38.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Unknown,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult,52.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult,64.0

In [ ]:
df[['Age', 'Age_Category']]

      Age Age_Category
0    22.0        Adult
1    38.0        Adult
2    26.0        Adult
3    35.0        Adult
4    35.0        Adult
..    ...          ...
886  27.0        Adult
887  19.0        Adult
888   NaN      Unknown
889  26.0        Adult
890  32.0        Adult

[891 rows x 2 columns]

In [ ]:

# ==========================================================
# MAP()
# ==========================================================

# Convert Gender into Numbers

gender_map = {
    "male":0,
    "female":1
}

df["Gender"] = df["Sex"].map(gender_map)

# Passenger Class Mapping

class_map = {
    1:"First Class",
    2:"Second Class",
    3:"Third Class"
}

df["Passenger_Class"] = df["Pclass"].map(class_map)

print(df[["Sex","Gender","Pclass","Passenger_Class"]].head())

In [ ]:
# ==========================================================
# APPLYMAP()
# ==========================================================

# Create Sample DataFrame

marks = pd.DataFrame({
    "Math":[80,70,90],
    "Science":[85,75,95],
    "English":[88,78,92]
})

print(marks)

# Increase Every Value by 5

marks = marks.applymap(lambda x: x+5)

print(marks)

# Convert Every Value into Percentage

marks = marks.applymap(lambda x: str(x)+" %")

print(marks)

In [ ]:

# ==========================================================
# LAMBDA FUNCTIONS
# ==========================================================

# Passenger Type

df["Passenger_Type"] = df["Age"].apply(
    lambda x: "Child" if x < 18 else "Adult"
)

# High Fare Passenger

df["Premium"] = df["Fare"].apply(
    lambda x: "Yes" if x > 100 else "No"
)

# Family or Solo Traveller

df["Traveller"] = (df["SibSp"] + df["Parch"]).apply(
    lambda x: "Family" if x > 0 else "Solo"
)

print(df[["Age","Passenger_Type","Fare","Premium","Traveller"]].head())

In [ ]:
def add(a, b):
  return a+b
def add(a , b , c):
  return a +b +c
add(1 , 2)

TypeError: add() missing 1 required positional argument: 'c'